# Generated by Django 2.1.7 on 2019-03-28 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0002_beer_beer_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beer',
            old_name='has_polikeg',
            new_name='has_polykeg',
        ),
    ]
