# Generated by Django 2.1.7 on 2019-03-28 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('beer', '0003_auto_20190328_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
