# Generated by Django 2.1.7 on 2019-03-31 21:19

import colorful.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0007_beerpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='contrast_background',
            field=colorful.fields.RGBColorField(default='#FBD872', verbose_name='Color used to contrast photos and graphics'),
        ),
        migrations.AlterField(
            model_name='beercategorypage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beer.BeerCategory', verbose_name='Page for category:'),
        ),
    ]
