# Generated by Django 2.1.7 on 2019-03-31 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0008_auto_20190331_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='short_description',
            field=models.TextField(default='Short description goes here', verbose_name='Short description'),
        ),
    ]
