# Generated by Django 2.1.7 on 2019-04-18 19:57

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0010_document_file_hash'),
        ('beer', '0009_beer_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeerContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Container name')),
                ('volume', models.IntegerField(default=0, verbose_name='Volume in cl')),
            ],
            options={
                'verbose_name': 'Beer Container',
                'verbose_name_plural': 'Beer Containers',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='beer',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='beer',
            name='degree_plato',
        ),
        migrations.RemoveField(
            model_name='beer',
            name='og',
        ),
        migrations.RemoveField(
            model_name='beer',
            name='srm',
        ),
        migrations.RemoveField(
            model_name='beer',
            name='tasting_appearance',
        ),
        migrations.RemoveField(
            model_name='beer',
            name='tasting_bitter',
        ),
        migrations.RemoveField(
            model_name='beer',
            name='tasting_smell',
        ),
        migrations.RemoveField(
            model_name='beer',
            name='tasting_sweet',
        ),
        migrations.RemoveField(
            model_name='beer',
            name='tasting_taste',
        ),
        migrations.AddField(
            model_name='beer',
            name='food_pairings',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Food pairings'),
        ),
        migrations.AddField(
            model_name='beer',
            name='infographic_icon',
            field=models.ForeignKey(blank=True, help_text='It shows bitterness, strength and colour', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document', verbose_name='Graphic icon for beer spec'),
        ),
        migrations.AddField(
            model_name='beercontainer',
            name='beers',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Beers availables for this kind of container', null=True, related_name='availabilities', to='beer.Beer', verbose_name='Beers'),
        ),
        migrations.AddField(
            model_name='beercontainer',
            name='svg_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
    ]
