# Generated by Django 2.1.7 on 2019-04-18 20:45

from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0010_auto_20190418_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='beercategory',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='beercontainer',
            name='beers',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Beers availables for this kind of container', related_name='availabilities', to='beer.Beer', verbose_name='Beers'),
        ),
    ]
