# Generated by Django 2.1.7 on 2019-04-18 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0012_auto_20190418_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='beercontainer',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
