# Generated by Django 2.1.7 on 2019-04-18 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0013_beercontainer_sort_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeerAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities_type', to='beer.Beer', verbose_name='Beer')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beers_available', to='beer.BeerContainer', verbose_name='Container')),
            ],
            options={
                'verbose_name': 'Beer Container',
                'verbose_name_plural': 'Beer Containers',
            },
        ),
    ]
