# Generated by Django 2.1.7 on 2019-04-18 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0015_auto_20190419_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beer',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='beercategory',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='beercontainer',
            name='sort_order',
        ),
    ]
