# Generated by Django 2.1.7 on 2019-04-18 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0016_auto_20190419_0100'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='beeravailability',
            unique_together={('beer', 'container')},
        ),
    ]
