# Generated by Django 2.1.7 on 2019-04-18 23:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0017_auto_20190419_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='beercategory',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='Created at'),
        ),
        migrations.AddField(
            model_name='beercategory',
            name='sort_order',
            field=models.PositiveIntegerField(default=1000, verbose_name='Order of display'),
        ),
        migrations.AddField(
            model_name='beercategory',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Update at'),
            preserve_default=False,
        ),
    ]
