# Generated by Django 2.1.7 on 2019-04-18 23:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0018_auto_20190419_0132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beer',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Beer', 'verbose_name_plural': 'Beers'},
        ),
        migrations.AlterModelOptions(
            name='beercategory',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Beer Category', 'verbose_name_plural': 'Beer Categories'},
        ),
        migrations.AlterModelOptions(
            name='beercontainer',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Beer Container', 'verbose_name_plural': 'Beer Containers'},
        ),
        migrations.AddField(
            model_name='beer',
            name='sort_order',
            field=models.PositiveIntegerField(default=1000, verbose_name='Displaying order'),
        ),
        migrations.AddField(
            model_name='beeravailability',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='Created at'),
        ),
        migrations.AddField(
            model_name='beeravailability',
            name='sort_order',
            field=models.PositiveIntegerField(default=1000, verbose_name='Displaying order'),
        ),
        migrations.AddField(
            model_name='beeravailability',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Update at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beercontainer',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='Created at'),
        ),
        migrations.AddField(
            model_name='beercontainer',
            name='sort_order',
            field=models.PositiveIntegerField(default=1000, verbose_name='Displaying order'),
        ),
        migrations.AddField(
            model_name='beercontainer',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Update at'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beer',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='beer',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Update at'),
        ),
        migrations.AlterField(
            model_name='beercategory',
            name='sort_order',
            field=models.PositiveIntegerField(default=1000, verbose_name='Displaying order'),
        ),
    ]
