# Generated by Django 2.1.7 on 2019-04-19 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0019_auto_20190419_0142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beer',
            name='how_to_store',
        ),
        migrations.AddField(
            model_name='beer',
            name='ingredients',
            field=models.CharField(default='Pay atention => Only the best natural ingredients.', max_length=512, verbose_name='How to store Lord Chambray'),
        ),
    ]
