# Generated by Django 2.1.7 on 2019-04-22 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0020_auto_20190419_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='ingredients',
            field=models.CharField(default='Pay atention => Only the best natural ingredients.', max_length=512, verbose_name='Beer ingredients'),
        ),
    ]
