# Generated by Django 2.1.7 on 2019-05-11 18:14

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtailgeowidget.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('puput', '0005_blogpage_main_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPage',
            fields=[
                ('entrypage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='puput.EntryPage')),
                ('details', wagtail.core.fields.StreamField([('details', wagtail.core.blocks.StructBlock([('start_date', wagtail.core.blocks.DateBlock()), ('start_time', wagtail.core.blocks.TimeBlock()), ('end_date', wagtail.core.blocks.DateBlock()), ('end_time', wagtail.core.blocks.TimeBlock()), ('address', wagtail.core.blocks.CharBlock()), ('location', wagtailgeowidget.blocks.GeoBlock(address_field='address', required=False))]))])),
            ],
            options={
                'abstract': False,
            },
            bases=('puput.entrypage',),
        ),
        migrations.CreateModel(
            name='TextSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Text Snippet name')),
                ('body', wagtail.core.fields.RichTextField(verbose_name='body')),
                ('classnames', models.CharField(blank=True, max_length=255, null=True, verbose_name='List of classname for css')),
            ],
            options={
                'verbose_name': 'Paragraph snippet',
                'verbose_name_plural': 'Paragraph snippets',
                'ordering': ['name'],
            },
        ),
    ]
