# Generated by Django 2.1.7 on 2019-03-28 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, help_text='Your Facebook page URL', max_length=255, null=True, verbose_name='Facebook Url')),
                ('instagram', models.URLField(blank=True, help_text='Your instagram page URL', max_length=255, null=True, verbose_name='Instagram Url')),
                ('twitter', models.URLField(blank=True, help_text='Your twitter page URL', max_length=255, null=True, verbose_name='Twitter Url')),
                ('youtube', models.URLField(blank=True, help_text='Your YouTube channel or user account URL', max_length=255, null=True, verbose_name='Twitter Url')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
