# Generated by Django 2.1.7 on 2019-03-29 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190328_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='slide_interval',
            field=models.IntegerField(default=5, verbose_name='Interval in seconds for the homepage slider'),
        ),
    ]
