# Generated by Django 2.1.7 on 2019-03-29 23:15

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import wagtailschemaorg.registry


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('home', '0005_homepage_slide_interval'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streetAddress', models.CharField(max_length=255, verbose_name='Street')),
                ('addressLocality', models.CharField(max_length=255, verbose_name='City')),
                ('addressRegion', models.CharField(max_length=4, verbose_name='Province/Region code es: TO for Torino')),
                ('postalCode', models.CharField(max_length=10, verbose_name='Zip code')),
                ('addressCountry', models.CharField(max_length=10, verbose_name='State ISO code, es IT')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrewerySettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptsReservations', models.BooleanField(verbose_name='Accepts reservation')),
                ('currenciesAccepted', models.CharField(help_text='Es [EUR, GBP]', max_length=255, verbose_name='Currencies Accepted')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('legal_name', models.CharField(max_length=100, verbose_name='Legal name')),
                ('vat_id', models.CharField(max_length=40, verbose_name='Vat ID number')),
                ('url', models.URLField(max_length=255, verbose_name='Site Url')),
                ('logo', models.URLField(max_length=255, verbose_name='Logo Url')),
                ('description', models.TextField(verbose_name='Description')),
                ('openingHours', models.CharField(help_text='Days are specified with two-letter combinations: Mo, Tu, We, Th, Fr, Sa, Su. Times are specified using 24:00 time. Example: "Tu,Th 16:00-20:00"', max_length=255, verbose_name='Opening hours')),
                ('foundingDate', models.CharField(max_length=4, verbose_name='Year of foundation')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.AddressSettings', verbose_name='Organization address')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtailschemaorg.registry.SiteThingLD, models.Model),
        ),
        migrations.CreateModel(
            name='ContactPointSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactType', models.CharField(max_length=255, verbose_name='Contact type es. Customer Support')),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Telephone number es +441719897979')),
                ('email', models.EmailField(max_length=254, verbose_name='Email address')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='brewerysettings',
            name='contactPoint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.ContactPointSettings', verbose_name='Contact point'),
        ),
        migrations.AddField(
            model_name='brewerysettings',
            name='same_as',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.SocialMediaSettings', verbose_name='Same as Social media accounts'),
        ),
        migrations.AddField(
            model_name='brewerysettings',
            name='site',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site'),
        ),
    ]
