# Generated by Django 2.1.7 on 2019-03-30 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190330_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='brewerysettings',
            name='priceRange',
            field=models.CharField(default='€€€', help_text='The price range of the business, for example €€€', max_length=5, verbose_name='How cheap is the brewery'),
            preserve_default=False,
        ),
    ]
