# Generated by Django 2.1.7 on 2019-04-27 23:36

from django.db import migrations, models
import django.db.models.deletion
import wagtail.search.index


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_brewerysettings_pricerange'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, unique=True, verbose_name='Logical description')),
                ('identifier', models.CharField(max_length=255, unique=True, verbose_name='Unique identifier to use in template')),
            ],
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='LinkPlacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_list', to='home.BaseSnippet')),
            ],
            options={
                'verbose_name': 'Link positioning',
                'verbose_name_plural': 'Link positionings',
            },
        ),
        migrations.CreateModel(
            name='LinkSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255, unique=True, verbose_name='Unique identifier to use in template')),
                ('link_text', models.CharField(max_length=255, verbose_name='Text to display')),
                ('url', models.URLField(max_length=512, verbose_name='Url for external page')),
            ],
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.AddField(
            model_name='linkplacement',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='home.LinkSnippet'),
        ),
    ]
