# Generated by Django 2.1.7 on 2019-04-28 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20190428_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkplacement',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_lists', to='home.BaseSnippet'),
        ),
    ]
