# Generated by Django 2.1.7 on 2019-04-28 00:09

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20190428_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkplacement',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='linkplacement',
            name='container',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_lists', to='home.BaseSnippet'),
        ),
    ]
